Repository CarlosZiegler/myinternship, pull requests merged in 2020-07, with the labels that each got.

#3 Add Cypres for E2E tests
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: enhancement

#20 Create Vacancy and User model with CRUD tests
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/configs/db.config.js.html
  coverage/lcov-report/configs/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/models/User.js.html
  coverage/lcov-report/models/Vacancy.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov-report/myinternship/configs/db.config.js.html
  coverage/lcov-report/myinternship/configs/index.html
  coverage/lcov-report/myinternship/index.html
  coverage/lcov-report/myinternship/models/User.js.html
  coverage/lcov-report/myinternship/models/Vacancy.js.html
  coverage/lcov-report/myinternship/models/index.html
  coverage/lcov-report/myinternship/sum.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  cypress/fixtures/profile.json
  cypress/fixtures/users.json
  jest.config.js
  models/User.js
  models/Vacancy.js
  package.json
  sum.js
  tests/connect-mongoDB.test.js
  tests/dbConnection.test.js
  tests/model-user.test.js
  tests/model-vacancy.test.js
  tests/sum.test.js
Labels: feature

#27 Authentication
  app.js
  package.json
  routes/auth.js
  routes/middlewares.js
  views/auth/login.hbs
  views/auth/signup.hbs
  yarn-error.log
  yarn.lock
Labels: feature

#29 try and cacth for Db queries in auth.js
  routes/auth.js
  views/auth/signup.hbs
Labels: enhancement

#28 Feature/vacancy routes
  app.js
  coverage/clover.xml
  coverage/lcov-report/configs/db.config.js.html
  coverage/lcov-report/configs/index.html
  coverage/lcov-report/index.html
  coverage/lcov-report/models/User.js.html
  coverage/lcov-report/models/Vacancy.js.html
  coverage/lcov-report/models/index.html
  models/User.js
  models/Vacancy.js
  public/stylesheets/styles.css
  routes/vacancy.js
  views/layout.hbs
  views/vacancy/addVacancy.hbs
  views/vacancy/detailsVacancy.hbs
  views/vacancy/editVacancy.hbs
  views/vacancy/listVacancies.hbs
Labels: feature

#31 add google authentication feature
  app.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/configs/db.config.js.html
  coverage/lcov-report/configs/index.html
  coverage/lcov-report/index.html
  coverage/lcov-report/models/User.js.html
  coverage/lcov-report/models/Vacancy.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov.info
  package.json
  routes/auth.js
  views/auth/login.hbs
Labels: feature

#33 Landing page
  public/images/bi_arrow-right-square-fill.png
  public/images/foundation_social-facebook.png
  public/images/foundation_social-github.png
  public/images/foundation_social-linkedin.png
  public/images/logo.png
  public/images/typcn_social-instagram.png
  public/images/undraw_feeling_proud_qne1.png
  public/stylesheets/styles.css
  views/index.hbs
  views/layout.hbs
Labels: feature

#37 Feature/main routes
  .github/workflows/node.js.yml
  app.js
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/configs/db.config.js.html
  coverage/lcov-report/configs/index.html
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/models/User.js.html
  coverage/lcov-report/models/Vacancy.js.html
  coverage/lcov-report/models/index.html
  coverage/lcov-report/myinternship/app.js.html
  coverage/lcov-report/myinternship/configs/db.config.js.html
  coverage/lcov-report/myinternship/configs/index.html
  coverage/lcov-report/myinternship/index.html
  coverage/lcov-report/myinternship/models/User.js.html
  coverage/lcov-report/myinternship/models/Vacancy.js.html
  coverage/lcov-report/myinternship/models/index.html
  coverage/lcov-report/myinternship/routes/auth.js.html
  coverage/lcov-report/myinternship/routes/index.html
  coverage/lcov-report/myinternship/routes/index.js.html
  coverage/lcov-report/myinternship/routes/vacancy.js.html
  coverage/lcov-report/myinternship/sum.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  public/images/briefcase1.png
  public/images/delete-icon.svg
  public/images/edit-icon.svg
  public/images/oie_6203557BRsjAIbs (1).png
  public/images/oie_6203557BRsjAIbs (2).png
  public/images/oie_6203557BRsjAIbs (4).png
  public/images/oie_6203557BRsjAIbs.png
  public/stylesheets/styles.css
  routes/auth.js
  routes/index.js
  routes/vacancy.js
  tests/vacancy-routes.test.js
  views/layout.hbs
  views/vacancy/addVacancy.hbs
  views/vacancy/detailsVacancy.hbs
  views/vacancy/editVacancy.hbs
  views/vacancy/listVacancies.hbs
  views/vacancy/listVacanciesPersonal.hbs
Labels: feature

#43 Feature/main routes
  .github/workflows/node.js.yml
  app.js
  public/images/check.svg
  public/images/heart.svg
  public/images/profile.svg
  public/stylesheets/styles.css
  routes/vacancy.js
  views/vacancy/addVacancy.hbs
  views/vacancy/detailsVacancy.hbs
  views/vacancy/editVacancy.hbs
  views/vacancy/listVacancies.hbs
  views/vacancy/listVacanciesPersonal.hbs
Labels: feature

#53 Feature/profile
  app.js
  routes/profile.js
  views/profile/details.hbs
Labels: feature

#59 button sendEmail function
  app.js
  routes/apply.js
  routes/helpers.js
  views/apply/vacancyApply.hbs
Labels: feature

#64 Feature/adjusts
  public/images/carbon_enterprise.svg
  public/images/undraw_feeling_proud_qne.svg
  public/stylesheets/styles.css
  routes/auth.js
  routes/vacancy.js
  views/apply/vacancyApply.hbs
  views/auth/login.hbs
  views/index.hbs
  views/layout.hbs
  views/vacancy/addVacancy.hbs
  views/vacancy/detailsVacancy.hbs
  views/vacancy/editVacancy.hbs
  views/vacancy/listVacancies.hbs
  views/vacancy/listVacanciesPersonal.hbs
  views/vacancy/myVacancies.hbs
Labels: bug
